version: '3'
services:
  app:
    container_name: spring-patent
    build: 
      context: ./patent
      args:
        JAR_FILE: build/libs/patent-0.0.1-SNAPSHOT.jar
    image: jaikar/patent-spring-boot-docker
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/redis-service/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"